name: probe-into-failure

on:
  workflow_dispatch:
    inputs:
      spec:
        description: 'single spec'
        required: true
        default: 'stories/story_tree_navigation.spec.js'
      commit:
        description: 'SHA of commit that triggered failed run'
        required: true
        default: '9a09afc1257eeeb0627709b2f10528193b008797'
      n_repeats:
        description: 'number of spec runs'
        required: true
        default: '3'

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{github.event.inputs.commit}}
      - name: download api artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          commit: ${{github.event.inputs.commit}}
          name: botfront-api-local
          path: .
      - name: download bf artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          commit: ${{github.event.inputs.commit}}
          name: botfront-local
          path: .
      - run: docker load < botfront-api-local.tar
      - run: docker load < botfront-local.tar
      - name: get versions
        id: versions
        run: |
          config=cli/project-template/.botfront/botfront.yml
          rasa=$(sed -n 's/\S*rasa: \(.*\)$/\1/p' $config | sed 's/.*://')
          echo ::set-output name=rasa::$rasa
      - name: cypress tests
        working-directory: ./botfront/cypress
        run: |
          mkdir -p mounted/models
          docker-compose \
          -f docker-compose-prober.yml \
          up \
          --abort-on-container-exit \
          --exit-code-from e2e
        env:
          RASA_TAG: ${{ steps.versions.outputs.rasa }}
          SPEC: ${{github.event.inputs.spec}}
          N_REPEATS: ${{github.event.inputs.n_repeats}}
      - name: save screenshots and videos
        uses: actions/upload-artifact@v1
        with:
          name: output
          path: ./botfront/cypress/output